# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jdromano.net
email: jdromano2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a data scientist and translational bioinformatics researcher,
  currently at Columbia University as a PhD student. This site showcases
  my personal and professional projects, as well as some other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdromano.net" # the base hostname & protocol for your site
twitter_username: jdromano2
github_username:  jdromano2

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
